### ISSUE TITLE
Adding TeHyBug relay to the TeHyBug website

### ISSUE THREAD

**Issue by 2m** [gumslone/tehybug#5]
I have successfully configured my TeHyBug relay to connect to my home wifi. And I can access TeHyBug relay consiguration page. But I am not able to find the TeHyBug Key needed to add the relay to the TeHyBug.com website.

**Comment by gumslone** [comment]
Hi,

with tasmota firmware there is no key, it means you can control the relay from the local network or you can allow remote access to it in your route (what I wouldn't recommend). Due to security concerns I've decided not to flash the devices with my own software which has the key and can be added and controlled via the site (i.e. someone could gain access to your account and control your relais).

**Comment by 2m** [comment]
I see. That makes sense.

My intention was to write a little task that would be scheduled periodically. It would check the temperature/humidity and would turn on or off the relay which would control air went in my bathroom.

I was thinking of writing this task in `repl.it` which would call the corresponding APIs hosted by `TeHyBug`. But since the relay is not available there, I will have to do it differently.

That script will have to run in my local network, because the relay is only available in the local network. So I think I will use RaspberryPI for running that script. And for automated deployment I will use https://www.balena.io/ which I have used before for deploying code to RaspberryPI with ease.
